### ISSUE TITLE
Google Colab Notebook

### ISSUE THREAD

**Issue by mogwai** [rbracco/fastai2_audio#17]
Setup a google colab notebook similar to what we did in the previous version:

https://colab.research.google.com/drive/1s0Ouw5PxvrmHdm_gBU0qiA6piOf3VSWO#scrollTo=Zda8aA0OKweb&forceEdit=true&sandboxMode=true

**Comment by PranY** [comment]
Does this [gist](https://colab.research.google.com/gist/PranY/ba0245752fff8ec2eb645afcc13f74f6/music.ipynb) answer this issue?

I recently used fastai2_audio for a classification pipeline and used most of its transforms. If you want I can update this gist with more examples on transforms.

Please let me know if this is what is needed otherwise do provide some guidelines.

**Comment by mogwai** [comment]
Yes that does seem to be what we need. Perhaps you could PR a link to in the readme?
