### ISSUE TITLE
Add Noise to Signal examples not working in 01_augement notebook

### ISSUE THREAD

**Issue by jdiedrick** [rbracco/fastai2_audio#5]
Running through this notebook, I couldn't get the Add Noise to Signal examples to work.

**Comment by rbracco** [comment]
Thanks for catching this Jo! I caused this mistake and it was due to a shift in the design of our transforms. Previously they created a copy and transformed that, but we have shifted to transforming in place, and the test object being transformed was not reinitialized before the transform was applied. We were applying the transform to an AudioItem that had been shifted/rolled 20x (for a timing test), and so it was actually shifted entirely out of frame, leaving an empty signal as the input to the Add Noise to Signal transform. 

I will PR a fix soon Adding the line `audio_orig = _audio_sc_ex()` before the transform should temporarily fix this issue.
